name = "DUI Squad Radar"
prefix = "diwako_dui"
author = "Diwako"
files = [
    "mod.cpp"
]
exclude = [
    "*.psd",
    "*.png",
    "*.tga"
]
# postbuild = ["!sign","!copy"]

releasebuild = [
    "@zip @{{prefix}}"
]
[scripts.copy]
foreach = true
only_release = true
steps = [
    "COPY {{target}} D:\\SteamLibrary\\steamapps\\common\\\"Arma 3\"\\@diwako_dui\\addons\\",
    "COPY {{target}}.diwako_dui.bisign D:\\SteamLibrary\\steamapps\\common\\\"Arma 3\"\\@diwako_dui\\addons\\"
]

[scripts.sign]
foreach = true
only_release = true
steps = [
    "G:\\\"Program Files (x86)\"\\Steam\\steamapps\\common\\\"Arma 3 Tools\"\\DSSignFile\\DSSignFile.exe diwako_dui.biprivatekey {{target}}"
]
